<?php

namespace EspritParcBundle\Repository;

/**
 * ModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll($pays){
        $dqlresult=$this->getEntityManager()
            ->createQuery("SELECT m FROM EspritParcBundle:Modele m WHERE m.pays='$pays'");
        return $dqlresult->getResult();
    }
}
