<?php

namespace EspritParcBundle\Repository;

/**
 * VoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoitureRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercheDate($datemc)
{ $dqlresult=$this->getEntityManager()->createQuery("SELECT V FROM EspritParcBundle:Voiture V WHERE V.datemc<:date")
    ->setParameter('date',$datemc);

    return $dqlresult->getResult();
}



    public function rechercheSerie($serie)
    { $dqlresult=$this->getEntityManager()->createQuery("SELECT V FROM EspritParcBundle:Voiture V WHERE V.serie=:serie")
        ->setParameter('serie',$serie);

        return $dqlresult->getResult();
    }

}
// dql ijib liste objets
// sql ijib des données linéaire